name = "grabber"
type = "javascript"
main = "build/index.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "./"

[build.upload]
format = "service-worker"

[env.production]
routes = [
  { pattern = "example.com/*", zone_name = "example.com" }
]
